theme: minima

title: Standards Android APP

Author: Saravanan M

description: Standards Android application helps to search, retrive and organise Bureau of Indian Standards (BIS).

tagline: Standards Android Apps for Bureau of Indian Standards (BIS) 

url: bisstandards.github.io/bisstandards

canonical_url: bisstandards.github.io/bisstandards

{% raw %}{% seo %}{% endraw %}
